### ISSUE TITLE
Biku won't work if songs are in different path than <OsuDir>\Songs

### ISSUE THREAD

**Issue by Lubieerror** [flesnuk/biku#1]
I'm working to fix it, and results are very promising...
![git-osusongdir](https://user-images.githubusercontent.com/11427815/32520106-1e5762ac-c40f-11e7-96a3-278d8a8c74c2.png)
Now I must just merge it into biku but I have hard week so if I won't have time you'll have to get "BeatmapDirectory" setting value from %Osu%\osu!.%windows_username%.cfg etc. 
You could also use parts of my code:
https://pastebin.com/LStb0z6F

**Comment by flesnuk** [comment]
Oh, I didn't know you could have the osu! songs outside the main osu! folder :stuck_out_tongue_closed_eyes:

Thanks for the detailed code and for looking into this. I will check it out and test it right now.

Edit: I think I got it working , tested with few song folder names containing spaces and so on, and it works fine. I will upload the changes today or tomorrow. :+1:
